version: "3.8"

services:
  api:
    build: .
    command: flask --app ./flaskr/__init__.py run --debug -h 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_started
    stdin_open: true
    tty: true

  db:
    image: mongo:8.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
